"""Enhance user career plan model

Revision ID: 08092f3c6598
Revises: 3ad063d7bf7f
Create Date: 2025-07-17 13:50:08.119980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08092f3c6598'
down_revision: Union[str, None] = '3ad063d7bf7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_career_plans', sa.Column('target_position', sa.Text(), nullable=True))
    op.add_column('user_career_plans', sa.Column('target_timeframe', sa.Text(), nullable=True))
    op.add_column('user_career_plans', sa.Column('specific_goals', sa.Text(), nullable=True))
    op.add_column('user_career_plans', sa.Column('personality_traits', sa.Text(), nullable=True))
    op.add_column('user_career_plans', sa.Column('preferred_learning_style', sa.Text(), nullable=True))
    op.add_column('user_career_plans', sa.Column('challenges_faced', sa.Text(), nullable=True))
    op.add_column('user_career_plans', sa.Column('motivation_factors', sa.Text(), nullable=True))
    op.drop_column('user_career_plans', 'goals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_career_plans', sa.Column('goals', mysql.TEXT(), nullable=True))
    op.drop_column('user_career_plans', 'motivation_factors')
    op.drop_column('user_career_plans', 'challenges_faced')
    op.drop_column('user_career_plans', 'preferred_learning_style')
    op.drop_column('user_career_plans', 'personality_traits')
    op.drop_column('user_career_plans', 'specific_goals')
    op.drop_column('user_career_plans', 'target_timeframe')
    op.drop_column('user_career_plans', 'target_position')
    # ### end Alembic commands ###
